// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGKo-jyhg9OVneePlmhVsiblI5Zm2fFFM',
    appId: '1:30119178931:web:b82efe32d42564aa9976c6',
    messagingSenderId: '30119178931',
    projectId: 'fir-flutter-codelab-345e2',
    authDomain: 'fir-flutter-codelab-345e2.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-345e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUAoGg4-QXUKImVpy8Bsx4sCMIh9N6eWc',
    appId: '1:30119178931:android:3942079ef43f1eb19976c6',
    messagingSenderId: '30119178931',
    projectId: 'fir-flutter-codelab-345e2',
    storageBucket: 'fir-flutter-codelab-345e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByiilq_yrDj_40xil7eA5S3Y8tTrQErGE',
    appId: '1:30119178931:ios:f0e1c4800b5fb6889976c6',
    messagingSenderId: '30119178931',
    projectId: 'fir-flutter-codelab-345e2',
    storageBucket: 'fir-flutter-codelab-345e2.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByiilq_yrDj_40xil7eA5S3Y8tTrQErGE',
    appId: '1:30119178931:ios:f0e1c4800b5fb6889976c6',
    messagingSenderId: '30119178931',
    projectId: 'fir-flutter-codelab-345e2',
    storageBucket: 'fir-flutter-codelab-345e2.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
